#if defined(DM_PLATFORM_ANDROID)

#ifndef DM_IAPC_EXTENSION
#define DM_IAPC_EXTENSION

enum TransactionState
{
    TRANS_STATE_PURCHASING = 0,
    TRANS_STATE_PURCHASED = 1,
    TRANS_STATE_FAILED = 2,
    TRANS_STATE_RESTORED = 3,
    TRANS_STATE_UNVERIFIED = 4,
};

enum ErrorReason
{
    REASON_UNSPECIFIED = 0,
    REASON_USER_CANCELED = 1,
};

enum BillingResponse
{
    BILLING_RESPONSE_RESULT_OK = 0,
    BILLING_RESPONSE_RESULT_USER_CANCELED = 1,
    BILLING_RESPONSE_RESULT_BILLING_UNAVAILABLE = 3,
    BILLING_RESPONSE_RESULT_ITEM_UNAVAILABLE = 4,
    BILLING_RESPONSE_RESULT_DEVELOPER_ERROR = 5,
    BILLING_RESPONSE_RESULT_ERROR = 6,
    BILLING_RESPONSE_RESULT_ITEM_ALREADY_OWNED = 7,
    BILLING_RESPONSE_RESULT_ITEM_NOT_OWNED = 8,
};

#endif // DM_IAPC_EXTENSION

#endif // DM_PLATFORM_ANDROID
